name: Forward epic field value into tracked issues

on:
  issues:
    types: [edited]

jobs:
  forward_epic_field_value:
    name: Forward epic field value into tracked issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install @octokit/action
      - run: node .github/actions/forward-project-field.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
          REPO_NAME: ${{ github.event.repository.name }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          PROJECT_ID: "PVT_kwDOAM0swc4ALoFY"
          FIELD_ID: "PVTSSF_lADOAM0swc4ALoFYzgJAimw"
          FIELD_NAME: Epic
